name: Changesets
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled, closed]
    branches:
      - main
  issue_comment:
    types: [edited]

env:
  CI: true
  NODE_OPTIONS: "--max-old-space-size=4096"

concurrency:
  group: ${{ github.event.number || github.event.issue.number }}

jobs:
  version:
    permissions: write-all
    name: static checks
    runs-on: ubuntu-22.04
    steps:
      - id: 'get-branch'
        uses: "gradio-app/github/actions/get-pr-branch@main"
        with:
          pr: ${{ github.event.number || github.event.issue.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          repository: ${{ steps.get-branch.outputs.repo }}
          ref: ${{ steps.get-branch.outputs.branch }}
          fetch-depth: 0
      - name: generate changeset
        uses: "gradio-app/github/actions/generate-changeset@main"
        with:
          github_token: ${{ secrets.PAT }}
          main_pkg: gradio
