name: Changesets
on:
  workflow_run:
    workflows: ["get-pr"]
    types:
      - completed

env:
  CI: true
  NODE_OPTIONS: "--max-old-space-size=4096"

concurrency:
  group: ${{ github.event.workflow_run.head_repository.full_name }}::${{ github.event.workflow_run.head_branch }}

jobs:
  version:
    permissions: write-all
    name: static checks
    runs-on: ubuntu-22.04
    steps:
      - id: 'get-pr'
        uses: "gradio-app/github/actions/get-pr-branch@main"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: get pr number
        run: echo "PR number is ${{ steps.get-pr.outputs.pr }}"